Map<int, String> langEng = {
  1 : "Clinic",
  2 : "Our Location",
  3 : "Home",
  4 : "Appointment",
  5 : "Messages",
  6 : "Account",
  7 : "Email ID",
  8 : "Password",
  9 : "Forgot password ?",
  10 : "Login",
  11 : "Don't have an account?",
  12 : "Signup",
  13 : "Enter Email ID",
  14 : "Enter Password",
  15 : "Create New Account",
  16 : "Email Verification!",
  17 : "Don't worry, we will find your account",
  18 : "Enter your email id",
  19 : "Please check your email we will send you one OTP on you email.",
  20 : "Send",
  21 : "Reset password email sended. Please check your mail.",
  22 : "Name",
  23 : "Enter your name",
  24 : "Enter your email id",
  25 : "Password",
  26 : "Enter your Password",
  27 : "Confirm Password",
  28 : "Already have an account?",
  29 : "LOGIN",
  30 : "By clicking ",
  31 : " you agree to the following",
  32 : "Privacy Policy",
  33 : "Enter password",
  34 : "Passwords are not equal",
  35 : "Email are wrong",
  36 : "Loading...",
  37 : "Log Out",
  38 : "Change Password",
  39 : "Enter Confirm Password",
  40 : "Password changed",
  41 : "New Password",
  42 : "Enter New Password",
  43 : "Confirm Password",
  44 : "Enter Confirm Password",
  45 : "Personal Info",
  46 : "Edit Your Name",
  47 : "Edit Your Email",
  48 : "Edit Your Contact number",
  49 : "Change Info",
  50 : "Data saved",
  51 : "Our specialists",
  52 : "Today",
  53 : "Search",
  54 : "No messages, yet.",
  55 : "User is disabled. Connect to Administrator for more information.",
  56 : "View all >>",
  57 : "Our Specialist",
  58 : "Services",
  59 : "min",
  60 : "Book Appointment",
  61 : "Appointment",
  62 : "Payment",
  63 : "Finished",
  64 : "Choose Specialist",
  65 : "Weekend",
  66 : "This is weekend",
  67 : "Please select service",
  68 : "Please select specialist",
  69 : "Total Pay",
  70 : "Cash payment",
  71 : "Confirm Payment",
  72 : "Something went wrong. ",
  73 : "Book More Appointment",
  74 : "Go to Appointments",
  75 : "Your Time:",
  76 : "Cancel",
  77 : "Are you sure?",
  78 : "Yes",
  79 : "No",
  80 : "Upcoming",
  81 : "Completed",
  82 : "Canceled",
  83 : "Complete",
  84 : "Rate",
  85 : "Enter your review",
  86 : "You rate ",
  87 : "No appointments",
  88 : "Special offers",
  89 : "from",
  90 : "to",
  91 : "Next",
  92 : "Payed",
  93 : "Not Paid",
  94 : "Minimum",
  95 : "Select Language",
  96 : "About us",
  97 : "Chat",
  98 : "Terms & Conditions",
  99 : "Message ...",
  100 : "Our works",
  101 : "Black mode",
  102 : "This specialist don't make",
  103 : "OTP verification",
  104 : "Phone number",
  105 : "Enter your phone number",
  106 : "Send Code",
  107 : 'Code sent. Please check your phone for the verification code.',
  108 : "Phone number must be ",
  109 : "symbols",
  110 : "Call to Clinic",
  111 : "Open Web Site",
  112 : "Open Instagram page",
  113 : "Share This App",
  114 : "Clinic",
  115 : "gallery",
  116 : "and other",
  117 : "NOW OPEN",
  118 : "NOW CLOSE",
  119 : "All salons",
  120 : "Select Clinica",
  121 : "Work Time for this Salon don't set",
  122 : "This is weekend for this master",
  123 : "No sort",
  124 : "By name A-Z",
  125 : "By name Z-A",
  126 : "Near me",
  127 : "Send Bug Report",
  128 : "Comment",
  129 : "Bug Report",
  130 : "Send Email",
  131 : "Your points",
  132 : "You have",
  133 : "points. Do you want to spend them?",
  134 : "Payment by points",
  135 : "points",
  136 : "Your points",
};

Map<int, String> langDeu = {
  1: "Clinic",
  2: "Unser Standort",
  3: "Zuhause",
  4: "Termin",
  5: "Nachrichten",
  6: "Konto",
  7: "E-Mail-ID",
  8: "Passwort",
  9: "Passwort vergessen?",
  10: "Login",
  11: "Sie haben noch keinen Account?",
  12: "Anmeldung",
  13: "E-Mail-ID eingeben",
  14: "Passwort eingeben",
  15: "Neues Konto erstellen",
  16: "E-Mail-Bestätigung!",
  17: "Mach dir keine Sorgen, wir werden dein Konto finden",
  18: "Geben Sie Ihre E-Mail-ID ein",
  19: "Bitte überprüfen Sie Ihre E-Mails. Wir senden Ihnen ein OTP per E-Mail.",
  20: "Senden",
  21: "Zurücksetzen der gesendeten Passwort-E-Mail. Bitte überprüfen Sie Ihre E-Mails.",
  22: "Name",
  23: "Geben Sie Ihren Namen ein",
  24: "Geben Sie Ihre E-Mail-ID ein",
  25: "Passwort",
  26: "Geben Sie Ihr Passwort ein",
  27: "Passwort bestätigen",
  28: "Haben Sie bereits einen Account?",
  29: "LOGIN",
  30: "Durch Klicken",
  31: "Sie stimmen dem Folgenden zu",
  32: "Datenschutzerklärung",
  33: "Passwort eingeben",
  34: "Passwörter sind nicht gleich",
  35: "E-Mail ist falsch",
  36: "Laden ...",
  37: "Abmelden",
  38: "Passwort ändern",
  39: "Passwort bestätigen",
  40: "Passwort geändert",
  41: "Neues Passwort",
  42: "Neues Passwort eingeben",
  43: "Passwort bestätigen",
  44: "Passwort bestätigen",
  45: "Persönliche Informationen",
  46: "Bearbeiten Sie Ihren Namen",
  47: "E-Mail bearbeiten",
  48: "Bearbeiten Sie Ihre Kontaktnummer",
  49: "Info ändern",
  50: "Daten gespeichert",
  51: "Unsere Spezialisten",
  52: "Heute",
  53: "Suche",
  54: "Noch keine Nachrichten.",
  55: "Benutzer ist deaktiviert. Stellen Sie eine Verbindung zum Administrator her, um weitere Informationen zu erhalten.",
  56: "Alle anzeigen >>",
  57: "Bester Spezialist",
  58: "Dienstleistungen",
  59: "min",
  60: "Buchtermin",
  61: "Termin",
  62: "Zahlung",
  63: "Fertig",
  64: "Spezialist auswählen",
  65: "Wochenende",
  66: "Dies ist Wochenende",
  67: "Bitte Service auswählen",
  68: "Bitte Spezialist auswählen",
  69: "Gesamtlohn",
  70: "Barzahlung",
  71: "Zahlung bestätigen",
  72: "Etwas ist schief gelaufen.",
  73: "Mehr Termin buchen",
  74: "Gehe zu Terminen",
  75: "Deine Zeit:",
  76: "Abbrechen",
  77: "Bist du sicher?",
  78: "Ja",
  79: "Nein",
  80: "Bevorstehend",
  81: "Abgeschlossen",
  82: "Abgebrochen",
  83: "Vollständig",
  84: "Rate",
  85: "Geben Sie Ihre Bewertung ein",
  86: "Sie bewerten",
  87: "Keine Termine",
  88: "Sonderangebote",
  89: "von",
  90: "bis",
  91: "Weiter",
  92: "Bezahlt",
  93: "Nicht bezahlt",
  94 : "Minimum",
  95 : "Sprache auswählen",
  96 : "Über uns",
  97 : "Chat",
  98 : "Allgemeine Geschäftsbedingungen",
  99 : "Nachricht ...",
  100 : "Unsere Werke",
  101 : "Schwarzmodus",
  102 : "Dieser Spezialist macht nicht\n",
  103 : "OTP-Überprüfung",
  104 : "Telefonnummer",
  105 : "Geben Sie Ihre Telefonnummer ein",
  106 : "Code senden",
  107 : 'Code gesendet. Bitte überprüfen Sie Ihr Telefon auf den Bestätigungscode.',
  108 : "Telefonnummer muss sein",
  109 : "Symbole",
  110 : "Anruf zum Salon",
  111 : "Website öffnen",
  112 : "Instagram-Seite öffnen",
  113 : "Diese App teilen",
  114 : "Salons",
  115 : "Galerie",
  116 : "und andere",
  117 : "JETZT GEÖFFNET",
  118 : "JETZT SCHLIESSEN",
  119 : "Alle Salons",
  120 : "Salon auswählen",
  121 : "Arbeitszeit für diesen Salon nicht eingestellt",
  122 : "Dies ist Wochenende für diesen Meister",
  123 : "Keine Sortierung",
  124 : "Nach Namen A-Z",
  125 : "Nach Namen Z-A",
  126 : "In meiner Nähe",
  127 : "Fehlerbericht senden",
  128 : "Kommentar",
  129 : "Fehlerbericht",
  130 : "E-Mail senden",
  131 : "Ihre Punkte",
  132 : "Du hast",
  133 : "Punkte. Möchten Sie sie ausgeben?",
  134 : "Zahlung nach Punkten",
  135 : "Punkte",
  136 : "Ihre Punkte",
};

Map<int, String> langEsp = {
  1: "Barbero",
  2: "Nuestra ubicación",
  3: "Inicio",
  4: "Cita",
  5: "Mensajes",
  6: "Cuenta",
  7: "ID de correo electrónico",
  8: "Contraseña",
  9: "¿Olvidaste tu contraseña?",
  10: "Iniciar sesión",
  11: "¿No tienes una cuenta?",
  12: "Registrarse",
  13: "Ingresar ID de correo electrónico",
  14: "Ingresar contraseña",
  15: "Crear nueva cuenta",
  16: "Verificación de correo electrónico",
  17: "No te preocupes, encontraremos tu cuenta",
  18: "Ingrese su ID de correo electrónico",
  19: "Por favor revise su correo electrónico, le enviaremos una OTP en su correo electrónico",
  20: "Enviar",
  21: "Se envió el correo electrónico para restablecer la contraseña. Revise su correo",
  22: "Nombre",
  23: "Ingrese su nombre",
  24: "Ingrese su ID de correo electrónico",
  25: "Contraseña",
  26: "Ingrese su contraseña",
  27: "Confirmar contraseña",
  28: "¿Ya tienes una cuenta?",
  29: "INICIAR SESIÓN",
  30: "Haciendo clic",
  31: "aceptas lo siguiente",
  32: "Política de privacidad",
  33: "Ingresar contraseña",
  34: "Las contraseñas no son iguales",
  35: "El correo electrónico es incorrecto",
  36: "Cargando ...",
  37: "Cerrar sesión",
  38: "Cambiar contraseña",
  39: "Ingrese Confirmar contraseña",
  40: "Contraseña cambiada",
  41: "Nueva contraseña",
  42: "Ingresar nueva contraseña",
  43: "Confirmar contraseña",
  44: "Ingrese Confirmar contraseña",
  45: "Información personal",
  46: "Edita tu nombre",
  47: "Editar su correo electrónico",
  48: "Edite su número de contacto",
  49: "Cambiar información",
  50: "Datos guardados",
  51: "Nuestros especialistas",
  52: "Hoy",
  53: "Buscar",
  54: "Aún no hay mensajes",
  55: "El usuario está deshabilitado. Conéctese con el administrador para obtener más información",
  56: "Ver todo >>",
  57: "Mejor especialista",
  58: "Servicios",
  59: "min",
  60: "Reservar cita",
  61: "Cita",
  62: "Pago",
  63: "Finalizado",
  64: "Elegir especialista",
  65: "Fin de semana",
  66: "Este es el fin de semana",
  67: "Seleccione el servicio",
  68: "Seleccione un especialista",
  69: "Pago total",
  70: "Pago en efectivo",
  71: "Confirmar pago",
  72: "Algo salió mal",
  73: "Reservar más cita",
  74: "Ir a citas",
  75: "Tu tiempo:",
  76: "Cancelar",
  77: "¿Estás seguro?",
  78: "Sí",
  79: "No",
  80: "Próximo",
  81: "Completado",
  82: "Cancelado",
  83: "Completo",
  84: "Calificar",
  85: "Ingrese su opinión",
  86: "Tu calificas",
  87: "Sin citas",
  88: "Ofertas especiales",
  89: "desde",
  90: "a",
  91: "Siguiente",
  92: "Pagado",
  93: "No pagado",
  94: "Mínimo",
  95: "Seleccionar idioma",
  96: "Acerca de nosotros",
  97: "Chat",
  98: "Términos y condiciones",
  99: "Mensaje ...",
  100: "Nuestras obras",
  101: "Modo negro",
  102: "Este especialista no hace \ n",
  103: "Verificación de OTP",
  104: "Número de teléfono",
  105: "Ingresa tu número de teléfono",
  106: "Enviar código",
  107: 'Código enviado. Por favor revise su teléfono para el código de verificación. ',
  108: "El número de teléfono debe ser",
  109: "símbolos",
  110: "Llamar al salón",
  111: "Abrir sitio web",
  112: "Abrir página de Instagram",
  113: "Compartir esta aplicación",
  114 : "Salons",
  115 : "Galerie",
  116 : "und andere",
  117 : "JETZT GEÖFFNET",
  118 : "JETZT SCHLIESSEN",
  119 : "Alle Salons",
  120 : "Salon auswählen",
  121 : "Arbeitszeit für diesen Salon nicht eingestellt",
  122 : "Dies ist Wochenende für diesen Meister",
  123: "Sin clasificación",
  124: "Por nombre A-Z",
  125: "Por nombre Z-A",
  126: "Cerca de mí",
  127: "Enviar informe de error",
  128: "Comentario",
  129: "Informe de error",
  130: "Enviar correo electrónico",
  131: "Tus puntos",
  132: "Tienes",
  133: "puntos. ¿Quieres gastarlos?",
  134: "Pago por puntos",
  135: "puntos",
  136: "Tus puntos",
};

Map<int, String> langFrench = {
  1: "Barbier",
  2: "Notre emplacement",
  3: "Accueil",
  4: "Rendez-vous",
  5: "Messages",
  6: "Compte",
  7: "Email ID",
  8: "Mot de passe",
  9: "Mot de passe oublié?",
  10: "Connexion",
  11: "Vous n'avez pas de compte?",
  12: "Inscription",
  13: "Saisir l'identifiant de l'e-mail",
  14: "Saisir le mot de passe",
  15: "Créer un nouveau compte",
  16: "Vérification des e-mails!",
  17: "Ne vous inquiétez pas, nous trouverons votre compte",
  18: "Entrez votre adresse e-mail",
  19: "Veuillez vérifier votre e-mail, nous vous enverrons un OTP sur votre e-mail.",
  20: "Envoyer",
  21: "Réinitialiser l'e-mail de mot de passe envoyé. Veuillez vérifier votre messagerie.",
  22: "Nom",
  23: "Entrez votre nom",
  24: "Entrez votre adresse e-mail",
  25: "Mot de passe",
  26: "Entrez votre mot de passe",
  27: "Confirmer le mot de passe",
  28: "Vous avez déjà un compte?",
  29: "CONNEXION",
  30: "En cliquant",
  31: "vous acceptez ce qui suit",
  32: "Politique de confidentialité",
  33: "Saisir le mot de passe",
  34: "Les mots de passe ne sont pas égaux",
  35: "Les e-mails sont erronés",
  36: "Chargement ...",
  37: "Déconnexion",
  38: "Changer le mot de passe",
  39: "Saisir le mot de passe",
  40: "Mot de passe modifié",
  41: "Nouveau mot de passe",
  42: "Saisir un nouveau mot de passe",
  43: "Confirmer le mot de passe",
  44: "Saisir le mot de passe",
  45: "Informations personnelles",
  46: "Modifier votre nom",
  47: "Modifier votre e-mail",
  48: "Modifier votre numéro de contact",
  49: "Modifier les informations",
  50: "Données enregistrées",
  51: "Nos spécialistes",
  52: "Aujourd'hui",
  53: "Rechercher",
  54: "Pas encore de messages.",
  55: "L'utilisateur est désactivé. Connectez-vous à l'administrateur pour plus d'informations.",
  56: "Voir tout >>",
  57: "Meilleur spécialiste",
  58: "Services",
  59: "min",
  60: "Prendre rendez-vous",
  61: "Rendez-vous",
  62: "Paiement",
  63: "Terminé",
  64: "Choisir un spécialiste",
  65: "Week-end",
  66: "C'est le week-end",
  67: "Veuillez sélectionner un service",
  68: "Veuillez sélectionner un spécialiste",
  69: "Salaire total",
  70: "Paiement en espèces",
  71: "Confirmer le paiement",
  72: "Une erreur s'est produite.",
  73: "Réserver plus de rendez-vous",
  74: "Aller aux rendez-vous",
  75: "Votre heure:",
  76: "Annuler",
  77: "Etes-vous sûr?",
  78: "Oui",
  79: "Non",
  80: "À venir",
  81: "Terminé",
  82: "Annulé",
  83: "Terminé",
  84: "Taux",
  85: "Donnez votre avis",
  86: "Vous évaluez",
  87: "Aucun rendez-vous",
  88: "Offres spéciales",
  89: "de",
  90: "à",
  91: "Suivant",
  92: "Payé",
  93: "Non payé",
  94 : "Minimum",
  95 : "Choisir la langue",
  96 : "A propos de nous",
  97 : "Chat",
  98 : "Conditions Générales",
  99 : "Message...",
  100 : "Nos oeuvres",
  101 : "Mode noir",
  102 : "Ce spécialiste ne fait pas\n",
  103 : "Vérification OTP",
  104 : "Numéro de téléphone",
  105 : "Entrez votre numéro de téléphone",
  106 : "Envoyer le code",
  107 : 'Code envoyé. Veuillez vérifier votre téléphone pour le code de vérification.',
  108 : "Le numéro de téléphone doit être ",
  109 : "symboles",
  110 : "Appel au Salon",
  111 : "Ouvrir le site Web",
  112 : "Ouvrir la page Instagram",
  113 : "Partager cette application",
  114 : "Salons",
  115 : "galerie",
  116 : "et autres",
  117 : "MAINTENANT OUVERT",
  118 : "MAINTENANT FERME",
  119 : "Tous les salons",
  120 : "Sélectionner Salon",
  121 : "Le temps de travail pour ce salon n'est pas défini",
  122 : "C'est le week-end pour ce maître",
  123 : "Pas de tri",
  124 : "Par nom A-Z",
  125 : "Par nom Z-A",
  126 : "Près de moi",
  127 : "Envoyer un rapport de bogue",
  128 : "Commentaire",
  129 : "Rapport de bogue",
  130 : "Envoyer un e-mail",
  131 : "Vos points",
  132 : "Vous avez",
  133 : "points. Voulez-vous les dépenser ?",
  134 : "Paiement par points",
  135 : "pointes",
  136 : "Vos points",
};


Map<int, String> langArabic = {
  1: "حلاق" ,
  2: "موقعنا" ,
  3: "الصفحة الرئيسية" ,
  4: "موعد" ,
  5: "الرسائل" ,
  6: "الحساب" ,
  7: "معرف البريد الإلكتروني" ,
  8: "كلمة المرور" ,
  9: "هل نسيت كلمة المرور؟" ,
  10: "تسجيل الدخول" ,
  11: "ليس لديك حساب؟" ,
  12: "الاشتراك" ,
  13: "أدخل معرف البريد الإلكتروني" ,
  14: "أدخل كلمة المرور" ,
  15: "إنشاء حساب جديد" ,
  16: "التحقق من البريد الإلكتروني!" ,
  17: "لا تقلق , سنجد حسابك" ,
  18: "أدخل معرف البريد الإلكتروني الخاص بك" ,
  19: "يرجى التحقق من بريدك الإلكتروني وسنرسل لك OTP واحدًا على بريدك الإلكتروني." ,
  20: "إرسال" ,
  21: "تم إرسال بريد إلكتروني لإعادة تعيين كلمة المرور. يرجى التحقق من بريدك." ,
  22: "الاسم" ,
  23: "أدخل اسمك" ,
  24: "أدخل معرف البريد الإلكتروني الخاص بك" ,
  25: "كلمة المرور" ,
  26: "أدخل كلمة المرور الخاصة بك" ,
  27: "تأكيد كلمة المرور" ,
  28: "هل لديك حساب بالفعل؟" ,
  29: "تسجيل الدخول" ,
  30: "بالنقر" ,
  31: "أنت توافق على ما يلي" ,
  32: "سياسة الخصوصية" ,
  33: "أدخل كلمة المرور" ,
  34: "كلمات المرور غير متساوية" ,
  35: "البريد الإلكتروني خاطئ" ,
  36: "جارٍ التحميل ..." ,
  37: "تسجيل الخروج" ,
  38: "تغيير كلمة المرور" ,
  39: "أدخل تأكيد كلمة المرور" ,
  40: "تم تغيير كلمة المرور" ,
  41: "كلمة المرور الجديدة" ,
  42: "أدخل كلمة المرور الجديدة" ,
  43: "تأكيد كلمة المرور" ,
  44: "أدخل تأكيد كلمة المرور" ,
  45: "المعلومات الشخصية" ,
  46: "عدل اسمك" ,
  47: "تحرير البريد الإلكتروني الخاص بك" ,
  48: "تحرير رقم الاتصال الخاص بك" ,
  49: "تغيير المعلومات" ,
  50: "البيانات المحفوظة" ,
  51: "المتخصصون لدينا" ,
  52: "اليوم" ,
  53: "بحث" ,
  54: "لا توجد رسائل , حتى الآن." ,
  55: "تم تعطيل المستخدم. اتصل بالمسؤول للحصول على مزيد من المعلومات.",
  56: "عرض الكل >>" ,
  57: "أفضل متخصص" ,
  58: "الخدمات" ,
  59: "دقيقة" ,
  60: "موعد الكتاب" ,
  61: "موعد" ,
  62: "الدفع" ,
  63: "انتهى" ,
  64: "اختر متخصص" ,
  65: "عطلة نهاية الأسبوع" ,
  66: "هذه عطلة نهاية الأسبوع" ,
  67: "الرجاء تحديد الخدمة" ,
  68: "الرجاء تحديد متخصص" ,
  69: "إجمالي الأجر" ,
  70: "الدفع النقدي" ,
  71: "تأكيد الدفع" ,
  72: "حدث خطأ ما" ,
  73: "احجز موعدًا أكثر" ,
  74: "الذهاب إلى المواعيد" ,
  75: "وقتك:" ,
  76: "إلغاء" ,
  77: "هل أنت متأكد؟" ,
  78: "نعم" ,
  79: "لا" ,
  80: "القادمة",
  81: "مكتمل" ,
  82: "ملغاة",
  83: "مكتمل" ,
  84: "معدل" ,
  85: "أدخل رأيك" ,
  86: "أنت تقيم" ,
  87: "لا توجد مواعيد" ,
  88: "العروض الخاصة" ,
  89: "from",
  90: "إلى" ,
  91: "التالي" ,
  92: "مدفوعة" ,
  93: "غير مدفوعة الأجر" ,
94: "الحد الأدنى" ,
95: "تحديد اللغة" ,
96: "عنا" ,
97: "دردشة" ,
98: "الشروط والأحكام" ,
99: "رسالة ..." ,
100: "أعمالنا" ,
101: "الوضع الأسود" ,
102: "هذا الاختصاصي لا يصنع \ n",
103: "التحقق من OTP" ,
104: "رقم الهاتف" ,
105: "أدخل رقم هاتفك" ,
106: "إرسال الرمز" ,
107:"    تم إرسال الرمز  . يرجى التحقق من هاتفك بحثًا عن رمز التحقق. ",
108: "يجب أن يكون رقم الهاتف" ,
109: "رموز" ,
110: "دعوة إلى الصالون" ,
111: "فتح موقع ويب" ,
112: "فتح صفحة Instagram" ,
113: "مشاركة هذا التطبيق",
  114: "صالونات" ,
  115: "معرض" ,
  116: "وغيرها" ,
  117: "مفتوح الآن" ,
  118: "NOW CLOSE" ,
  119: "جميع الصالونات" ,
  120: "سيليكت صالون" ,
  121: "لم يتم تعيين وقت العمل لهذا الصالون" ,
  122: "هذه عطلة نهاية الأسبوع لهذا المعلم" ,
  123: "بدون فرز" ,
  124: "بالاسم أ-ي" ,
  125: "بالاسم ي-أ" ,
  126: "بالقرب مني" ,
  127: "إرسال تقرير خطأ" ,
  128: "تعليق" ,
  129: "تقرير الخطأ" ,
  130: "إرسال بريد إلكتروني" ,
  131: "نقاطك" ,
  132: "لديك" ,
  133: "النقاط. هل تريد أن تنفقها؟" ,
  134: "الدفع بالنقاط" ,
  135: "نقطة" ,
  136: "نقاطك" ,
};


Map<int, String> langPort = {
  1: "Clinica",
  2: "Nossa localização",
  3: "Casa",
  4: "Compromisso",
  5: "Mensagens",
  6: "Conta",
  7: "ID de e-mail",
  8: "Senha",
  9: "Esqueceu a senha?",
  10: "Login",
  11: "Não tem conta?",
  12: "Inscrição",
  13: "Insira o ID do e-mail",
  14: "Digite a senha",
  15: "Criar nova conta",
  16: "Verificação de Email!",
  17: "Não se preocupe, encontraremos sua conta",
  18: "Digite seu ID de e-mail",
  19: "Por favor, verifique seu e-mail, nós lhe enviaremos um OTP em seu e-mail.",
  20: "Enviar",
  21: "E-mail de redefinição de senha enviado. Verifique seu e-mail.",
  22: "Nome",
  23: "Digite seu nome",
  24: "Digite seu ID de e-mail",
  25: "Senha",
  26: "Digite sua senha",
  27: "Confirmar senha",
  28: "Já tem uma conta?",
  29: "LOGIN",
  30: "Ao clicar",
  31: "você concorda com o seguinte",
  32: "Política de Privacidade",
  33: "Digite a senha",
  34: "As senhas não são iguais",
  35: "Email está errado",
  36: "Carregando ...",
  37: "Sair",
  38: "Alterar senha",
  39: "Digite a senha de confirmação",
  40: "Senha alterada",
  41: "Nova senha",
  42: "Digite a nova senha",
  43: "Confirmar senha",
  44: "Digite a senha de confirmação",
  45: "Informações pessoais",
  46: "Edite seu nome",
  47: "Edite seu e-mail",
  48: "Edite seu número de contato",
  49: "Alterar Informações",
  50: "Dados salvos",
  51: "Nossos especialistas",
  52: "Hoje",
  53: "Pesquisar",
  54: "Ainda não há mensagens.",
  55: "O usuário está desabilitado. Conecte-se ao administrador para obter mais informações.",
  56: "Ver todos >>",
  57: "Melhor Especialista",
  58: "Serviços",
  59: "min",
  60: "Agendar Consulta",
  61: "Compromisso",
  62: "Pagamento",
  63: "Concluído",
  64: "Escolha um especialista",
  65: "Fim de semana",
  66: "Este é o fim de semana",
  67: "Selecione o serviço",
  68: "Selecione um especialista",
  69: "Pagamento Total",
  70: "Pagamento em dinheiro",
  71: "Confirmar Pagamento",
  72: "Algo deu errado.",
  73: "Agendar Mais Consulta",
  74: "Vá para Compromissos",
  75: "Seu tempo:",
  76: "Cancelar",
  77: "Tem certeza?",
  78: "Sim",
  79: "Não",
  80: "Próximos",
  81: "Concluído",
  82: "Cancelado",
  83: "Completo",
  84: "Avaliar",
  85: "Insira seu comentário",
  86: "Você avalia",
  87: "Sem compromissos",
  88: "Ofertas especiais",
  89: "de",
  90: "para",
  91: "Próximo",
  92: "Pago",
  93: "Não pago",
  94: "Mínimo",
  95: "Selecione o idioma",
  96: "Sobre nós",
  97: "Bate-papo",
  98: "Termos e Condições",
  99: "Mensagem ...",
  100: "Nossas obras",
  101: "Modo preto",
  102: "Este especialista não faz",
  103: "Verificação OTP",
  104: "Número de telefone",
  105: "Digite o seu número de telefone",
  106: "Enviar Código",
  107: 'Código enviado. Por favor, verifique seu telefone para o código de verificação. ',
  108: "O número do telefone deve ser",
  109: "símbolos",
  110: "Chamada para o salão de beleza",
  111: "Abrir Site",
  112: "Abrir página Instagram",
  113: "Compartilhar este aplicativo",
  114: "Salões",
  115: "galeria",
  116: "e outro",
  117: "AGORA ABERTO",
  118: "AGORA CLOSE",
  119: "Todos os salões",
  120: "Selecionar salão",
  121: "Horário de trabalho para este salão não definido",
  122: "Este é o fim de semana para este mestre",
  123: "Sem classificação",
  124: "Por nome A-Z",
  125: "Por nome Z-A",
  126: "Perto de mim",
  127: "Enviar relatório de bug",
  128: "Comentário",
  129: "Relatório de Bug",
  130: "Enviar e-mail",
  131: "Seus pontos",
  132: "Você tem",
  133: "pontos. Quer gastá-los?",
  134: "Pagamento por pontos",
  135: "pontos",
  136: "Seus pontos",
};

Map<int, String> langRus = {
  1: "Парикмахер",
  2: "Наше местонахождение",
  3: "Дом",
  4: "Встреча",
  5: "Сообщения",
  6: "Учетная запись",
  7: "Идентификатор электронной почты",
  8: "Пароль",
  9: "Забыли пароль?",
  10: "Вход",
  11: "Нет учетной записи?",
  12: "Регистрация",
  13: "Введите адрес электронной почты",
  14: "Введите пароль",
  15: "Создать новую учетную запись",
  16: "Подтверждение адреса электронной почты!",
  17: "Не волнуйтесь, мы найдем ваш аккаунт",
  18: "Введите свой адрес электронной почты",
  19: "Пожалуйста, проверьте свою электронную почту, мы отправим вам один OTP на вашу электронную почту.",
  20: "Отправить",
  21: "Отправлено электронное письмо для сброса пароля. Пожалуйста, проверьте свою почту.",
  22: "Имя",
  23: "Введите свое имя",
  24: "Введите свой адрес электронной почты",
  25: "Пароль",
  26: "Введите пароль",
  27: "Подтвердите пароль",
  28: "Уже есть учетная запись?",
  29: "ВХОД",
  30: "По щелчку",
  31: "вы соглашаетесь со следующим",
  32: "Политика конфиденциальности",
  33: "Введите пароль",
  34: "Пароли не равны",
  35: "Неправильный адрес электронной почты",
  36: "Загрузка ...",
  37: "Выйти",
  38: "Изменить пароль",
  39: "Введите пароль для подтверждения",
  40: "Пароль изменен",
  41: "Новый пароль",
  42: "Введите новый пароль",
  43: "Подтвердите пароль",
  44: "Введите пароль для подтверждения",
  45: "Личная информация",
  46: "Измени свое имя",
  47: "Изменить адрес электронной почты",
  48: "Измените свой контактный номер",
  49: "Изменить информацию",
  50: "Данные сохранены",
  51: "Наши специалисты",
  52: "Сегодня",
  53: "Поиск",
  54: "Сообщений пока нет.",
  55: "Пользователь отключен. Для получения дополнительной информации обратитесь к администратору.",
  56: "Посмотреть все >>",
  57: "Лучший специалист",
  58: "Услуги",
  59: "мин",
  60: "Запись на прием",
  61: "Назначение",
  62: "Оплата",
  63: "Готово",
  64: "Выбрать специалиста",
  65: "Выходные",
  66: "Это выходные",
  67: "Выберите услугу",
  68: "Выберите специалиста",
  69: "Общая оплата",
  70: "Наличный расчет",
  71: "Подтвердить платеж",
  72: "Что-то пошло не так.",
  73: "Забронировать больше встречи",
  74: "Перейти к встречам",
  75: "Ваше время:",
  76: "Отменить",
  77: "Вы уверены?",
  78: "Да",
  79: "Нет",
  80: "Скоро",
  81: "Завершено",
  82: "Отменено",
  83: "Завершено",
  84: "Ставка",
  85: "Введите свой отзыв",
  86: "Вы оцениваете",
  87: "Никаких встреч",
  88: "Специальные предложения",
  89: "от",
  90: "к",
  91: "Далее",
  92: "Выплачено",
  93: "Не оплачено",
94: "Минимум",
95: "Выбрать язык",
96: "О нас",
97: "Чат",
98: "Положения и условия",
99: "Сообщение ...",
100: "Наши работы",
101: "Черный режим",
102: "Этот специалист не делает \ n",
103: "Проверка OTP",
104: "Номер телефона",
105: "Введите свой номер телефона",
106: "Отправить код",
107: "Код отправлен. Проверьте свой телефон на наличие кода подтверждения. ",
108: "Номер телефона должен быть",
109: "символы",
110: "Звонок в салон",
111: "Открытый веб-сайт",
112: "Открыть страницу в Instagram",
113: "Поделиться этим приложением",
  114: "Салоны",
  115: "галерея",
  116: "и прочее",
  117: "ТЕПЕРЬ ОТКРЫТО",
  118: "ТЕПЕРЬ ЗАКРЫТЬ",
  119: "Все салоны",
  120: "Выбрать салон",
  121: "Время работы для этого Салона не назначено",
  122: "Это выходные для этого мастера",
123: "Нет",
124: "По имени А-Я",
125: "По имени Z-A",
126: "Рядом со мной",
127: "Отправить отчет об ошибке",
128: "Комментарий",
129: "Отчет об ошибке",
130: "Отправить электронное письмо",
131: "Ваши очки",
132: "Есть",
133: "Очки. Вы хотите их потратить?",
134: "Оплата баллами",
135: "точки",
136: "Ваши очки",
};